FROM node:lts-bookworm AS dependencies
WORKDIR /
COPY ./site/intelvision/package.json .
RUN npm install

FROM node:lts-alpine3.20 AS deploy
RUN mkdir -p /home/node/app/node_modules && chown -R node:node /home/node/app
WORKDIR /
COPY --from=dependencies ./node_modules ./node_modules
COPY ./site/intelvision .
EXPOSE 8080
CMD ["node", "app.js"]
